data:
  batch_size: 512
  csv_path: data/data_existing_image_paths.csv
  image_cache_dir: data/raw/images
  image_path_column: image_path
  image_size: 224
  image_url_column: image_url
  keep_min_samples_per_label: 10
  label_column: taxon_id
  label_names_column: common_name
  num_classes: 387
  num_workers: 6
  seed: 42
  test_size: 0.15
  uuid_column: uuid
  validation_size: 0.15
evaluation:
  min_accuracy: 0.05
  min_f1: 0.05
  min_precision: 0.05
  min_recall: 0.05
inference:
  input_image_path: /Users/anugrah/Desktop/Projects/animal-classifier-mlops/data/new_raw/images/0a0aa06a-fcdd-4194-8f33-609d05833b8d.jpg
  model_version: 1
  model_path: models/best_model.pth
  pipeline_name: deployment_pipeline
  pipeline_step_name: mlflow_model_deployer_step
  running: false
  service_wait_seconds: 20
train:
  device: cuda
  epochs: 25
  lr: 1.0e-05
  max_lr: 0.0001
  mlflow_model_name: animal-classifier-resnet50
  model_name: resnet50
  optimizer: adamw
  pretrained: true
  save_best_only: true
  save_dir: models
  scheduler: onecyclelr
