base:
  environment: local
  data:
    csv_path: ../data/data.csv
    uuid_column: uuid
    image_url_column: image_url
    image_url_fallback_column: url
    label_column: taxon_id
    label_names_column: common_name
    keep_min_samples_per_label: 10
    validation_size: 0.15
    test_size: 0.15
    num_workers: 4
    image_size: 224
    normalize_mean: [0.485, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    augmentations: true
    image_cache_dir: ../data/raw/images
    sample_limit: null
  model:
    num_classes: null
    in_channels: 3
    conv_filters: [64, 128, 256, 512, 512]
    conv_layers_per_block: [2, 2, 3, 3, 3]
    kernel_size: 3
    dropout: 0.3
    hidden_dim: 1024
    second_hidden_dim: 512
    use_batch_norm: true
    use_spectral_norm: false
  training:
    experiment_name: animal_species_multiclass
    full_training: false
    epochs: 50
    batch_size: 512
    gradient_clip_norm: 5.0
    amp: true
    early_stopping_patience: 5
    optimizer:
      name: adamw
      lr: 0.01
      weight_decay: 0.01
    scheduler:
      name: onecycle
      max_lr: 0.001
    seed: 42
    device: cuda
    baseline: resnet18
  tuning:
    enabled: false
    num_samples: 16
    max_epochs: 20
    grace_period: 3
    metric: val_accuracy
    mode: max
    search_space:
      lr:
        loguniform: [0.00005, 0.001]
      weight_decay:
        loguniform: [1.0e-06, 0.0005]
      dropout:
        uniform: [0.1, 0.5]
      batch_size:
        choice: [32, 64, 128, 256]
    resources_per_trial:
      cpu: 2
      gpu: 1
  deployment:
    enable: true
    mode: process
    evaluation:
      min_precision: 0.05
      min_recall: 0.05
      min_accuracy: 0.1
      metric_key: val_accuracy
    mlflow_model_name: AnimalSpeciesClassifier
    serving_host: 127.0.0.1
    serving_port: 5001
    server_env: {}
    healthcheck_timeout: 90
    external_service_url: null
  inference:
    batch_size: 16
    max_concurrency: 4
    latency_threshold_ms: 500.0
    tolerance_precision_delta: 0.05
    tolerance_recall_delta: 0.05
  logging:
    level: INFO
    log_dir: ../logs
    log_file: pipeline.log
  storage:
    mlflow_tracking_uri: http://127.0.0.1:5000
    mlflow_registry_uri: null
    s3_bucket: animal-species-feedback
    s3_region: us-east-1
  validation:
    enable: true
    deepchecks:
      enabled: true
      output_dir: ../outputs/validation
      html_report_name: deepchecks_report.html
      max_samples_per_split: 2000
      random_seed: 42
  metadata:
    author: ml-team
    description: Animal species classification pipeline

environments:
  ci:
    model:
      conv_filters: [32, 64, 128, 128]
      conv_layers_per_block: [2, 2, 2, 2]
      hidden_dim: 512
      second_hidden_dim: 256
      dropout: 0.4
    training:
      epochs: 1
      batch_size: 8
    tuning:
      enabled: false
    deployment:
      enable: false
  prod:
    model:
      conv_filters: [64, 128, 256, 512, 512]
      conv_layers_per_block: [2, 2, 3, 3, 3]
      hidden_dim: 1024
      second_hidden_dim: 512
      dropout: 0.35
    training:
      device: cuda
      epochs: 40
    tuning:
      num_samples: 20
      max_epochs: 20
    deployment:
      evaluation:
        min_precision: 0.8
        min_recall: 0.8
  docker:
    storage:
      mlflow_tracking_uri: http://mlflow:5000
    deployment:
      mode: external
      serving_host: model-server
      serving_port: 5001
      external_service_url: http://model-server:5001/invocations
